#!/bin/sh
# Enspired by https://codeinthehole.com/tips/tips-for-using-a-git-pre-commit-hook/

STASH_NAME="pre-commit.$(date +%F.%T)"
git stash push -q --keep-index --include-untracked -m $STASH_NAME
STASH_TITLE="On $(git rev-parse --abbrev-ref HEAD): ${STASH_NAME}"



./test.sh
RESULT=$?

STASH_LAST=$(git stash list -1 --pretty=%B)

if [ "$STASH_LAST" = "$STASH_TITLE" ]
then
    git stash pop -q
else
    echo Last stash is not mine
fi

exit $RESULT