#!/bin/bash
MY_DIR=$(dirname "$(realpath "$0")")
CMD="$1"; shift
subdirs="commands hooks utils"

for subdir in $(echo $subdirs | xargs); do
  if [ -f "$MY_DIR/$subdir/$CMD" ]
  then
    $MY_DIR/$subdir/$CMD $@ 
    exit $?
  fi
done

echo "Unknown command. Available:"
for subdir in $(echo $subdirs | xargs); do
  echo "# $subdir:" | tr '[:lower:]' '[:upper:]';
  find "$MY_DIR/$subdir" -type f -exec basename {} \; | sort | sed 's/^/- /'
done

exit 1
