#!/bin/bash
DIR=$(realpath "$(dirname "$(realpath "$0")")/..")
ME=$(basename "$(realpath "$0")")
HOOKSCONF=$DIR/hooks_dir
HOOK=$(cat $HOOKSCONF)/$ME

test -f $HOOK
if [ $? -ne 0 ]
then
 echo -e "\033[33mNo $ME hook '$HOOK'- skipped\033[0m";
 exit 0;
fi

echo -e "\033[30;43m<$ME>\033[0m \033[4m$HOOK\033[0m"

_exit() {
  if [ "$1" != 0 ]
    then
      echo -e "Failed\n\033[30;41m</$ME>\033[0m" 
    else
      echo -e "\033[30;42m</$ME>\033[0m" 
  fi
  exit $1
}
