#!/bin/bash
MY_DIR=$(dirname "$(realpath "$0")")
CMD="$1"; shift
subdirs="scripts hooks utils"

for subdir in $(echo $subdirs | xargs); do
  test -f "$MY_DIR/$subdir/$CMD"
  if [ $? == 0 ]
  then
    $MY_DIR/$subdir/$CMD $@ 
    exit $?
  fi
done

echo "Unknown command. Available:"
for subdir in $(echo $subdirs | xargs); do
  echo "# $subdir:" | tr '[:lower:]' '[:upper:]';
  find "./$subdir" -type f -exec basename {} \; | sort | sed 's/^/- /'
done

exit 1
