#!/bin/bash
WRAPPERS_PATH=$(dirname "$(realpath "$0")")
WRAPPERS_PATH=$(realpath "$WRAPPERS_PATH/../hooks")
HOOKS_PATH="${1:-git-hooks}"

echo -n "$HOOKS_PATH" > "$WRAPPERS_PATH/../hooks_dir"

git config --local core.hooksPath "$WRAPPERS_PATH"
# Windows MINGW stuff
CONFIGED=$(git config --get core.hooksPath | \
sed -e 's/^\([A-Z]\):/\/\1/' | \
tr '[:upper:]' '[:lower:]')
WRAPPERS_PATH=$(echo $WRAPPERS_PATH | tr '[:upper:]' '[:lower:]')
if [ "$CONFIGED" == "$WRAPPERS_PATH" ]
then
  echo "Wrapped git hooks in folder '$HOOKS_PATH'"
  exit 0
else 
  echo "hooksPathPath wasn't applied - received '$CONFIGED'.\nRun manually: git config --local core.hooksPath \"$WRAPPERS_PATH\""
  exit 1
fi
